name: "Run Tests"

on:
  workflow_dispatch:
  pull_request:

jobs:

  run-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Maven and JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Run tests
      run: mvn test

      # Build Docker image
    - name: Build Docker image
      run: docker build .
